### PR TITLE
fix: `consistent-type-specifier-style` with `prefer-inline` and TS resolution-mode import attributes

### LINKED ISSUE #233: `consistent-type-specifier-style`: Add exception for `resolution-mode` import attributes
In TypeScript, you can force a type module resolution to be either ESM or CJS with the following:

```ts
import type {Foo} from 'some-package' with {'resolution-mode': 'import'};
```

This is documented here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-3.html#stable-support-resolution-mode-in-import-types

However, TypeScript only allows this when the `type` is top-level. In other words, this gives a compiler error:

```ts
import {type Foo} from 'some-package' with {'resolution-mode': 'import'};
// ^ Error: `resolution-mode` can only be set for type-only imports.
```

This is a problem when `import-x/consistent-type-specifier-style` is set to `prefer-inline`. The rule option shouldn't warn in this case.

### PR DESCRIPTION
**Pull request by baevm**
fixes #233. not sure is it right way to place tests in TS_ONLY array as its TS only feature or in COMMON_TESTS?

----

> [!IMPORTANT]
> Add handling for TypeScript `resolution-mode` attribute in `consistent-type-specifier-style` rule to prevent incorrect linting.
> 
>   - **Behavior**:
>     - Add `hasResolutionModeAttribute()` in `consistent-type-specifier-style.ts` to check for `resolution-mode` attribute in import declarations.
>     - Skip rule enforcement if `resolution-mode` attribute is present.
>   - **Tests**:
>     - Add test cases for `resolution-mode` attribute in `consistent-type-specifier-style.spec.ts` under `TS_ONLY`.
>     - Ensure both `prefer-inline` and `prefer-top-level` options are tested with `resolution-mode`.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=un-ts%2Feslint-plugin-import-x&utm_source=github&utm_medium=referral)<sup> for 126a59cf1f5bc9fdf386139461023cd457283a6a. You can [customize](https://app.ellipsis.dev/un-ts/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

## Summary by CodeRabbit

* **Bug Fixes**
  * The consistent-type-specifier-style lint rule now preserves imports that include a resolution-mode attribute, avoiding transformations for both configuration options.

* **Tests**
  * Added coverage confirming type-only imports with resolution-mode attributes are valid under both prefer-inline and prefer-top-level.

* **Chores**
  * Added a changeset and updated the changelog entry for this fix.

### CODE REVIEW

File: src/rules/consistent-type-specifier-style.ts [hunk 1]
```diff
@@ -44,6 +44,17 @@ function getImportText(
   return `import ${kind} {${names.join(', ')}} from ${sourceString};`
 }
 
+// https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-3.html#stable-support-resolution-mode-in-import-types
+function hasResolutionModeAttribute(node: TSESTree.ImportDeclaration) {
+  return (
+    node.attributes &&
+    node.attributes.some(
```
Comment (JounQin) [inline src/rules/consistent-type-specifier-style.ts]:
```suggestion
    node.attributes &&
    node.attributes?.some(
```

File: src/rules/consistent-type-specifier-style.ts [hunk 2]
```diff
@@ -44,6 +44,17 @@ function getImportText(
   return `import ${kind} {${names.join(', ')}} from ${sourceString};`
 }
 
+// https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-3.html#stable-support-resolution-mode-in-import-types
+function hasResolutionModeAttribute(node: TSESTree.ImportDeclaration) {
+  return (
+    node.attributes &&
```
Comment (JounQin) [inline src/rules/consistent-type-specifier-style.ts]:
```suggestion
```

**Review by JounQin — APPROVED** [review]
