### PR TITLE
Fix windows support

### LINKED ISSUE #212: Adding windows support
Whilst fixing #211 I discovered that a lot of the rules (seemingly the ones using minimatch) don't work on Windows. I can see that windows is commented out in `.github.yml`: https://github.com/un-ts/eslint-plugin-import-x/blob/c3950d4a9ec341bed44b40f1807ca74e00db5ae0/.github/workflows/ci.yml#L19

I'd be happy to raise a PR to fix any existing test issues so that windows can be fully supported, if that would be welcome?

### PR DESCRIPTION
**Pull request by mrginglymus**
- Fixes #212

### CODE REVIEW

File: src/rules/no-extraneous-dependencies.ts [hunk 1]
```diff
@@ -335,7 +335,9 @@ function testConfig(config: string[] | boolean | undefined, filename: string) {
   }
   // Array of globs.
   return config.some(
-    c => minimatch(filename, c) || minimatch(filename, path.resolve(c)),
+    c =>
+      minimatch(filename, c) ||
+      minimatch(filename, path.resolve(c).replaceAll(path.sep, '/')),
```
Comment (SukkaW) [inline src/rules/no-extraneous-dependencies.ts:340]: We could extract a `normalizePath` utility that does this.

**Comment by mrginglymus** [comment]
Hmm, the attempt to remove those symlinks has gone badly...

File: src/utils/glob-resolve.ts [hunk 2]
```diff
@@ -0,0 +1,8 @@
+import path from 'node:path'
+
+/**
+ * Wrapper around `path.resolve` that replaces all `path.sep` with `/` to ensure it remains a valid glob pattern.
+ */
+export const globResolve = (...paths: string[]): string => {
+  return path.resolve(...paths).replaceAll(path.sep, '/')
+}
```
Comment (SukkaW) [inline src/utils/glob-resolve.ts:8]: I am not sure about this. Does that mean we need to implement `globJoin` and `globRelative` in the future as well?

IMHO we might want to use https://www.npmjs.com/package/normalize-path instead of self-baking this one.

Comment (mrginglymus) [reply src/utils/glob-resolve.ts]: Hopefully not. I'm not too sure about adding the dep; it's slower and more complex than `replaceAll` for the use case required here, which is almost always just about turning a glob into an absolute path.

If instead we didn't pass in the file location as an absolute path but as a relative path to cwd, we wouldn't need to resolve the glob at all.

Comment (mrginglymus) [reply src/utils/glob-resolve.ts]: Though looking at it, assumptions of absolute paths are pretty well baked in.

Comment (mrginglymus) [reply src/utils/glob-resolve.ts]: https://github.com/un-ts/eslint-plugin-import-x/blob/1ff90b846d294c54c7965db0ceb481e9bf9ed968/src/rules/no-relative-packages.ts#L16-L18 

oh look!

I agree a dedicated globResolve is a bit pointless, better to just convert to posix paths at the point of minimatching (by moving that function out to a utils folder) _or_ to say that all backslashes are path separators, which is what is currently pushed.

**Review by SukkaW — APPROVED** [review]

File: test/rules/no-absolute-path.spec.ts [hunk 3]
```diff
@@ -66,72 +62,72 @@ ruleTester.run('no-absolute-path', rule, {
...
     tInvalid({
-      code: `import f from "${absolutePath('/foo')}"`,
-      filename: absolutePath('/foo/bar/index.js'),
+      code: `import f from "/foo"`,
+      filename: '/foo/bar/index.js',
       errors: [ABSOLUTE_ERROR],
       output: 'import f from ".."',
     }),
     tInvalid({
-      code: `import f from "${absolutePath('/foo/bar/baz.js')}"`,
```
Comment (JounQin) [inline test/rules/no-absolute-path.spec.ts:75]: I don't quite understand this change, it doesn't cover Windows absolute paths.

Comment (mrginglymus) [reply test/rules/no-absolute-path.spec.ts:75]: It's not possible to do an absolute path import on Windows - or at least, I couldn't work out how to make one.

Comment (JounQin) [reply test/rules/no-absolute-path.spec.ts:75]: https://github.com/nodejs/node/issues/31710

`file://` protocol can be used for Windows absolute path, but of course we maybe not handling `file://` protocol previously, same as other protocols like `http://` or `https://`.

But in case that `file://` is only for absolute local path like previous, it could be an improvement.

Comment (mrginglymus) [reply test/rules/no-absolute-path.spec.ts:75]: Yes, using a file protocol path seems like a different question to a posix absolute path - or at least an additional feature to be added to this rule.
