### PR TITLE
fix: make `extensions` handle `.d.ts` correctly

### LINKED ISSUE #164: How to configure import-x/extensions to enforce .js
Hi,

I recently switched from eslint-plugin-import to this package, thanks for taking over. 
Most things are drop-in replacements but I'm struggling with `import-x/extensions` in Typescript env.

No matter what I'm configuring it's always asking to add `.ts` extension, while it works with bun and bundler, it's not correct when targeting node. Is there a way to configure it to ask for `.js`? Or did I misconfigure something?

```ts
 'import-x/extensions': [
    'error',
    'always',
      {
          json: 'always',
          js: 'always',
          ts: 'never',
          ignorePackages: true,
     },
 ],
```

Thanks in advance

### PR DESCRIPTION
**Pull request by silverwind**
When importing `.js` and a `.d.ts` file with the same name exists, like for example when importing from a `dist` directory, the rule incorrectly demanded the import to be changed to `.ts` (a non-existing file).

Likely fixes https://github.com/un-ts/eslint-plugin-import-x/issues/164.

## Summary by CodeRabbit

* **Bug Fixes**
  * Corrected extension detection so TypeScript declaration variants (.d.ts, .d.mts, .d.cts) are recognized during import resolution, preserving normal behavior for regular files.

* **Tests**
  * Added a test case covering type-declaration resolution where a .js import resolves to a declaration file.

* **New Files**
  * Added example module and matching type declaration used by the new test.

* **Chores**
  * Added a changeset entry for a patch release.

### CODE REVIEW

**Comment by silverwind** [comment]
@coderabbitai retry

File: src/rules/extensions.ts [hunk 1]
```diff
@@ -328,9 +328,15 @@ export default createRule<Options, MessageId>({
...
         const resolvedPath = resolve(importPath, context)
 
-        // get extension from resolved path, if possible.
-        // for unresolved, use source value.
-        const extension = path.extname(resolvedPath || importPath).slice(1)
+        // get extension from resolved path, or source value if unresolved.
+        // for .d.ts/.d.mts/.d.cts, use the import path extension instead.
+        const extension = path
+          .extname(
+            resolvedPath && /\.d\.[cm]?ts$/.test(resolvedPath)
```
Comment (SukkaW) [inline src/rules/extensions.ts]: Maybe hoist the regexp here?

**Review by SukkaW — APPROVED** [review]
LGTM overall, except a small nitpick.

File: src/rules/extensions.ts (hunk 1 above)
Comment (silverwind) [reply src/rules/extensions.ts]: Done in https://github.com/un-ts/eslint-plugin-import-x/pull/468/commits/c88eac0d32db0c8fb3f6f17ac50a994ba25df2de.

**Review by SukkaW — APPROVED** [review]
