### PR TITLE
feat(extensions): support `pathGroupOverrides` and `fix` options

### LINKED ISSUE #318: Port enhance import extension enforcement with autofix support
Just think this is a great PR that's been sitting idle on the parent GitHub repo:

* https://github.com/import-js/eslint-plugin-import/pull/3177
* https://github.com/import-js/eslint-plugin-import/issues/1749

### PR DESCRIPTION
**Pull request by JounQin**
close #318
close #326

----

> [!IMPORTANT]
> Enhances `extensions` rule with `pathGroupOverrides` and `fix` options, updates documentation, and expands tests.
> 
>   - **Behavior**:
>     - Adds `pathGroupOverrides` and `fix` options to `extensions` rule in `extensions.ts`.
>     - Supports selective enforcement based on import path patterns.
>     - Introduces automatic fixing and suggestions for import path extensions.
>   - **Utilities**:
>     - Adds `parsePath` and `stringifyPath` functions in `parse-path.ts` for handling path strings.
>   - **Documentation**:
>     - Updates `extensions.md` and `README.md` to document new rule options and fixability.
>   - **Tests**:
>     - Expands tests in `extensions.spec.ts` for new options and TypeScript scenarios.
>     - Adds `parse-path.spec.ts` to test new utility functions.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=un-ts%2Feslint-plugin-import-x&utm_source=github&utm_medium=referral)<sup> for 1474a62315661b4d5770cecef44790e8e96567e4. You can [customize](https://app.ellipsis.dev/un-ts/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

----

## Summary by CodeRabbit

- **New Features**
  - Enhanced the import extensions rule with support for path group overrides, allowing selective enforcement based on import path patterns.
  - Introduced automatic fixing and suggestions for missing or unwanted import path extensions.
  - Added new utility functions for parsing and stringifying path strings.

- **Documentation**
  - Updated rule documentation and README to reflect new fixability and override features.
  - Added detailed notes on automatic and manual fixing options.

- **Tests**
  - Expanded test coverage for the extensions rule, including autofix, override patterns, and TypeScript scenarios.
  - Added tests for the new path parsing utility.

### CODE REVIEW

File: src/rules/extensions.ts [hunk 1]
```diff
@@ -286,6 +395,14 @@ export default createRule<Options, MessageId>({
               extension,
               importPath: importPathWithQueryString,
             },
+            ...(props.fix && {
```
Comment (JounQin) [inline src/rules/extensions.ts:398]: Let's also add suggestions here.

File: src/utils/parse-path.ts [hunk 2]
```diff
@@ -0,0 +1,25 @@
+export interface ParsedPath {
+  pathname: string
+  query: string
+  hash: string
+}
+
+export const parsePath = (path: string): ParsedPath => {
```
Comment (JounQin) [inline src/utils/parse-path.ts:7]: @stephenjason89 You'd better to use this pattern to support `?`/`#` better in 
original `importPath` for https://github.com/import-js/eslint-plugin-import/pull/3177

File: src/rules/extensions.ts [hunk 3]
```diff
@@ -261,17 +332,55 @@ export default createRule<Options, MessageId>({
...
+            !overrideAction && isPackage,
           )
           const extensionForbidden = isUseOfExtensionForbidden(extension)
           if (extensionRequired && !extensionForbidden) {
+            const { pathname, query, hash } = parsePath(
+              importPathWithQueryString,
+            )
+            const fixedImportPath = stringifyPath({
+              pathname: `${
+                /([\\/]|[\\/]?\.?\.)$/.test(pathname)
```
[the remark this answers is not in the document]
Comment (JounQin) [reply src/rules/extensions.ts:344]: @stephenjason89 You also need to change your `fix` implementation.

**Comment by stephenjason89** [comment]
Hey, I appreciate that the changes were used and improved with tests — thank you for that. That said, I would’ve really preferred if my original PR was merged and any follow-up changes were pushed to my branch or discussed first. It would’ve felt more collaborative and helped retain proper credit for the initial effort.

I hope future contributions can follow that approach. Thanks again.

**Comment by JounQin** [comment]
> Next time I’ll make sure to allow edits on the branch so things can move more smoothly. Looking forward to contributing more 🙌

> I believe that's because your fork is based on https://github.com/import-js/eslint-plugin-import instead of this repo, so I got no permission to push changes to your fork.

https://github.com/un-ts/eslint-plugin-import-x/pull/326#issuecomment-2890997487

File: src/rules/extensions.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (stephenjason89) [reply src/rules/extensions.ts:344]: Will do. Thanks!

File: src/utils/parse-path.ts (hunk 2 above)
Comment (stephenjason89) [reply src/utils/parse-path.ts:7]: Got it.
