### PR TITLE
fix: take `context.cwd` into account for cache key

### LINKED ISSUE #370: (VSCode) False positive of rule import-x/no-unresolved in monorepo with multiple packages open
Hello! Im having the following issue when using VSCode with Eslint and Import-x. I'm opening this issue here because this is the only package where the issue arises, all other work properly. If this is not correct, please let me know

I have monorepo setup with a shared config file. there, I have "bundles" of plugins that my apps and packages can use. The bundle that sets up this extension is the following:

```ts
import { createTypeScriptImportResolver } from 'eslint-import-resolver-typescript';
import { importX } from 'eslint-plugin-import-x';
import noRelativeImportPaths from 'eslint-plugin-no-relative-import-paths';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  importX.flatConfigs.recommended,
  importX.flatConfigs.typescript,
  {
    settings: {
      'import-x/resolver-next': [
        createTypeScriptImportResolver({
          project: [
            'tsconfig.json',
            'apps/*/tsconfig.json',
            'packages/*/tsconfig.json',
          ],
          alwaysTryTypes: true,
        }),
      ],
    },
  },
  {
    rules: { //... },
  },
);
```

This works well in the case I open just one app (lets say I open the workspace `apps/my-app-1` directly instead of the root directory of the monorepo. However, when I open the root directory, i have the following behavior:
 
- I open a file inside  `apps/my-app-1`, then the extension detects imports properly, without issues
- After opening the previous file, I open any file in `apps/my-app-2`, then the extension fails to find the local aliased imports:
Image

It seems to me like there's an issue with the path alias `@/` that is not being updated when I change apps inside the monorepo, but I could be totally wrong. 

I have created a small reproduction link, with instructions in the readme:
https://github.com/auirarrazaval/import-x-bug-no-unresolved-bug

### PR DESCRIPTION
**Pull request by JounQin**
close #370

related https://github.com/microsoft/vscode-eslint/issues/1994

`process.cwd()`/`context.cwd` can be changed with `process.cwd('new path')`

----

> [!IMPORTANT]
> Fix cache key generation by including `context.cwd` to improve cache accuracy and reduce collisions.
> 
>   - **Bug Fix**:
>     - Include `context.cwd` in cache key generation in `export-map.ts` and `module-cache.ts` to improve cache accuracy and reduce collisions.
>   - **Refactor**:
>     - Replace `module.isBuiltin` with `isBuiltin` in `node-resolver.ts`.
>     - Update `CacheKey` type to `string` in `module-cache.ts`.
>     - Add `NormalizedCacheSettings` interface in `types.ts` for cache settings.
>   - **Tests**:
>     - Update tests in `resolve.spec.ts` to validate cache key changes and ensure correct module resolution behavior.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=un-ts%2Feslint-plugin-import-x&utm_source=github&utm_medium=referral)<sup> for 8311c98008f3b6f4c0533863c441ee12b9268862. You can [customize](https://app.ellipsis.dev/un-ts/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

----

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved cache accuracy by including the current working directory in cache key generation, reducing potential cache collisions.

- **Refactor**
  - Updated and clarified cache-related settings and types for improved consistency and reliability.
  - Enhanced internal logic for module resolution and cache management to streamline performance and maintainability.

- **Chores**
  - Added documentation for a patch update to the package.

### CODE REVIEW

File: src/utils/module-cache.ts [hunk 1]
```diff
@@ -23,18 +22,18 @@ export class ModuleCache {
...
-      if (process.hrtime(f.lastSeen)[0] < settings.lifetime) {
-        return f!.result as T
+      if (process.hrtime(cache.lastSeen)[0] < settings.lifetime) {
+        return cache.result as T
       }
     } else {
       log('cache miss for', cacheKey)
     }
     // cache miss
+    clearNodeResolverCache()
```
Comment (JounQin) [inline src/utils/module-cache.ts]: We may need to add an optional `clearResolveCache` method into v3 interface?

cc @43081j @SukkaW

File: src/utils/export-map.ts [hunk 2]
```diff
@@ -1114,27 +1122,35 @@ function childContext(
...
+    filename,
+    physicalFilename,
   }
 }
 
 export function makeContextCacheKey(context: RuleContext | ChildContext) {
   const { settings, parserPath, parserOptions, languageOptions } = context
 
   let hash =
+    process.cwd() +
```
Comment (SukkaW) [inline src/utils/export-map.ts]: Is ESLint's `context.cwd` safe here? `process.cwd()` is heavy and could hurt performance.

Comment (JounQin) [reply src/utils/export-map.ts]: I'm not sure, cc @dbaeumer

File: src/utils/module-cache.ts (hunk 1 above)
Comment (SukkaW) [reply src/utils/module-cache.ts]: That's weird. TBH, this `ModuleCache` is only a TTL map that respects fs `mtime`. I am really not a fan of a double cache layer here.

What about adding the `cacheTtl` option to `unrs-resolver`, and we simply pass `settings.lifetime` to that? And then we can safely throw away this `ModuleCache`.

Or if we don't touch `unrs-resolver` and retain the `ModuleCache`, we might just disable `unrs-resolver`'s cache completely.

Comment (JounQin) [reply src/utils/module-cache.ts]: There could be 3rd-party resolvers, their own cache is not cleared previously, so without a new `clearResolveCache` method, 3rd-party's cache can never be cleared, for example `eslint-import-resolver-oxc`.

File: src/utils/export-map.ts (hunk 2 above)
Comment (dbaeumer) [reply src/utils/export-map.ts]: @JounQin `context.cwd` should be fine. I set it here: https://github.com/microsoft/vscode-eslint/blob/main/server/src/eslint.ts#L1148

Comment (SukkaW) [reply src/utils/export-map.ts]: Nice! Also, this basically "caches" the `process.cwd`, thus no performance penalty during linting!

File: src/utils/module-cache.ts (hunk 1 above)
Comment (SukkaW) [reply src/utils/module-cache.ts]: IIUC, `clearNodeResolverCache` is trying to clear `unrs-resolver`'s cache instead of `ModuleCache`'s map?

Comment (JounQin) [reply src/utils/module-cache.ts]: Yes.

Comment (SukkaW) [reply src/utils/module-cache.ts]: So we have 2 cache layers here:

- `ModuleCache`. This is a TTL map that respects files' `mtime`. If the source file changes, `mtime` changes, and the cache auto invalidates. We don't need to manually clear this cache at all. If this cache is hit, no resolve request will ever reach any resolvers (oxc, unrs, nothing).
- `unrs-resolver`'s cache: It is internal, will only be used if `ModuleCache` misses.

TBH, we'd either all-in `ModuleCache` (completely disable `unrs-resolver`'s cache), or just make `unrs-resolver`'s cache respect `mtime` as well.

We don't need to expose a clear cache method if there is no cache or if the cache can invalidate itself.

Comment (JounQin) [reply src/utils/module-cache.ts]: As I mentioned above, 3rd-party resolvers like `eslint-import-resolver-oxc` has no chance to clear its own cache, it's not only about `unrs-resolver`, and according to https://github.com/jestjs/jest/issues/15660 and https://github.com/jestjs/jest/pull/15666, a singleton resolver instance with reused cache has much better performance.

Actually I want to do the opposite, the resolvers should respect the cache settings instead, we shouldn't cache for all resolvers which could be unexpected for 3rd-party resolvers, so my original proposal is adding an optional `clearResolveCache` method.

Comment (SukkaW) [reply src/utils/module-cache.ts]: > As I mentioned above, 3rd-party resolvers like `eslint-import-resolver-oxc` has no chance to clear its own cache

I have not caught up yet. Why do you want to clear the resolvers' cache on `eslint-plugin-import-x`'s internal `ModuleCache` miss? Does `eslint-plugin-import-x`'s internal cache have anything to do with downstream resolvers?

> we shouldn't cache for all resolvers which could be unexpected for 3rd-party resolvers

The resolve process should be immutable and deterministic: given an importer, an importee, and an array of resolvers executing in the specified order, there should only be one possible result. So there is nothing wrong with caching the resolving results outside of the resolver.

Comment (JounQin) [reply src/utils/module-cache.ts]: I think I'm wrong here to include using singleton resolver instance in this PR, I'll revert back, this is happening because we're fallback legacy v1/v2 `node` resolver into v3 interface, and when using a global singleton resolver instance, there will be a falling test case because it's testing cache invalidation.

File: .changeset/major-apples-invent.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"eslint-plugin-import-x": patch
+---
+
+fix: take `process.cwd()` into account for cache key
```
Comment (JounQin) [inline .changeset/major-apples-invent.md]:
```suggestion
fix: take `context.cwd` into account for cache key
```

File: src/utils/module-cache.ts (hunk 1 above)
Comment (JounQin) [reply src/utils/module-cache.ts]: @SukkaW Are we good here now?

Comment (SukkaW) [reply src/utils/module-cache.ts]: I believe the PR could continue now.

**Review by SukkaW — APPROVED** [review]
